apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
  name: nginx
  namespace: from-argocd-mgmt
spec:
  containers:
  - image: nginx
    name: nginx
---
apiVersion: v1
kind: Namespace
metadata:
  name: from-argocd-mgmt
